using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NSL.Entity.PathGenerator
{
    [Generator]
    public class PathTableGenerator : IIncrementalGenerator
    {
        // Формат для typeof(), который игнорирует nullable-аннотации (без '?')
        private static readonly SymbolDisplayFormat TypeOfFormat = new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.UseSpecialTypes
        );

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "NSL.Entity.PathGenerator.Shared.Annotations.PathTableAttribute",
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
                .Where(symbol => symbol != null);

            // 1. Генерируем таблицы для каждой сущности
            context.RegisterSourceOutput(provider, (spc, symbol) => Execute(spc, symbol));

            // 2. Собираем все сущности и генерируем центральный реестр
            var collectedEntities = provider.Collect();
            context.RegisterSourceOutput(collectedEntities, (spc, symbols) => ExecuteRegistry(spc, symbols));
        }

        private void Execute(SourceProductionContext spc, INamedTypeSymbol entity)
        {
            var sb = new StringBuilder();
            var namespaceName = entity.ContainingNamespace.ToDisplayString();
            var entityName = entity.Name;

            var joinAttrs = entity.GetAttributes()
                .Where(a => a.AttributeClass != null && a.AttributeClass.Name == "PathJoinAttribute")
                .ToList();

            var modelJoins = new List<Tuple<string, string[]>>();
            foreach (var attr in joinAttrs)
            {
                if (attr.ConstructorArguments.Length == 2)
                {
                    var targetModel = attr.ConstructorArguments[0].Value as string;
                    var sourceModels = attr.ConstructorArguments[1].Values
                        .Select(v => v.Value as string)
                        .Where(v => v != null)
                        .ToArray();

                    if (!string.IsNullOrEmpty(targetModel) && sourceModels.Length > 0)
                    {
                        modelJoins.Add(Tuple.Create(targetModel, sourceModels));
                    }
                }
            }

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq.Expressions;");
            sb.AppendLine("");
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {entityName}PathTable");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly IReadOnlyDictionary<string, NSL.Entity.PathGenerator.Shared.FilterInfo> Map = new Dictionary<string, NSL.Entity.PathGenerator.Shared.FilterInfo>");
            sb.AppendLine("        {");

            foreach (var prop in entity.GetMembers().OfType<IPropertySymbol>())
            {
                var pathNodeAttr = prop.GetAttributes().FirstOrDefault(a => a.AttributeClass != null && a.AttributeClass.Name == "PathNodeAttribute");
                if (pathNodeAttr == null) continue;

                var baseModelsList = pathNodeAttr.ConstructorArguments.FirstOrDefault().Values
                    .Select(v => v.Value as string)
                    .Where(v => v != null)
                    .ToList();

                var expandedModels = new HashSet<string>(baseModelsList);
                if (baseModelsList.Count > 0)
                {
                    foreach (var join in modelJoins)
                    {
                        var targetMassive = join.Item1;
                        var sources = join.Item2;

                        foreach (var source in sources)
                        {
                            if (expandedModels.Contains(source))
                            {
                                expandedModels.Add(targetMassive);
                                break;
                            }
                        }
                    }
                }
                var finalModels = expandedModels.ToArray();

                bool isCollection = TryGetElementType(prop.Type, out ITypeSymbol elementType);
                var actualType = isCollection ? elementType : prop.Type;

                bool hasNestedMap = actualType.GetAttributes().Any(a => a.AttributeClass != null && a.AttributeClass.Name == "PathTableAttribute");
                var nestedMapFunc = hasNestedMap ? $"() => {actualType.ContainingNamespace}.{actualType.Name}PathTable.Map" : "null";

                var proxyMappings = GetProxyMappings(prop, finalModels);

                // --- НОВЫЙ БЛОК: Чтение CanBeNull ---
                bool canBeNull = prop.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T ||
                                 prop.NullableAnnotation == NullableAnnotation.Annotated;

                // --- НОВЫЙ БЛОК: Сборка PathMeta ---
                var metaEntries = new List<string>();
                var metaAttrs = prop.GetAttributes().Where(a => a.AttributeClass != null && a.AttributeClass.Name == "PathMetaAttribute");
                foreach (var attr in metaAttrs)
                {
                    if (attr.ConstructorArguments.Length == 2)
                    {
                        var k = attr.ConstructorArguments[0].Value as string;
                        var v = attr.ConstructorArguments[1].Value;
                        if (k != null && v != null)
                        {
                            if (v is string)
                            {
                                v = $"\"{v}\"";
                            }

                            metaEntries.Add($"{{ \"{k}\", {v} }}");
                        }
                    }
                }

                string metaDictString = metaEntries.Count > 0
                    ? "new Dictionary<string, object> { " + string.Join(", ", metaEntries) + " }"
                    : "new Dictionary<string, object>()";

                foreach (var mapping in proxyMappings)
                {
                    var segmentName = mapping.Key;
                    var specificModels = mapping.Value;

                    string modelsStr = specificModels.Length > 0
                        ? "new string[] { " + string.Join(", ", specificModels.Select(m => $"\"{m}\"")) + " }"
                        : "Array.Empty<string>()";

                    // Безопасное имя типа без `?`
                    var cleanTypeName = prop.Type.ToDisplayString(TypeOfFormat);
                    var cleanElementTypeName = isCollection ? elementType.ToDisplayString(TypeOfFormat) : "null";

                    sb.AppendLine($"            [\"{segmentName}\"] = new NSL.Entity.PathGenerator.Shared.FilterInfo(");
                    sb.AppendLine($"                typeof({cleanTypeName}),");
                    sb.AppendLine($"                (Expression<Func<{entityName}, {prop.Type.ToDisplayString()}>>)(x => x.{prop.Name}),");
                    sb.AppendLine($"                {nestedMapFunc},");
                    sb.AppendLine($"                {isCollection.ToString().ToLower()},");
                    sb.AppendLine($"                {(isCollection ? $"typeof({cleanElementTypeName})" : "null")},");
                    sb.AppendLine($"                {modelsStr},");
                    sb.AppendLine($"                {canBeNull.ToString().ToLower()},");
                    sb.AppendLine($"                {metaDictString}");
                    sb.AppendLine($"            ),");
                }
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{entityName}PathTable.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        // --- НОВЫЙ МЕТОД: Генерация центрального реестра ---
        private void ExecuteRegistry(SourceProductionContext spc, ImmutableArray<INamedTypeSymbol> symbols)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("");
            sb.AppendLine("namespace NSL.Entity.PathGenerator");
            sb.AppendLine("{");
            sb.AppendLine("    public static class PathTableRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly IReadOnlyDictionary<Type, IReadOnlyDictionary<string, NSL.Entity.PathGenerator.Shared.FilterInfo>> AllMaps = new Dictionary<Type, IReadOnlyDictionary<string, NSL.Entity.PathGenerator.Shared.FilterInfo>>");
            sb.AppendLine("        {");

            // Избавляемся от дубликатов на всякий случай
            var distinctSymbols = symbols.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>();

            foreach (var entity in distinctSymbols)
            {
                var fullTypeName = entity.ToDisplayString(TypeOfFormat);
                var mapAccess = $"{entity.ContainingNamespace}.{entity.Name}PathTable.Map";

                sb.AppendLine($"            [typeof({fullTypeName})] = {mapAccess},");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("PathTableRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private bool TryGetElementType(ITypeSymbol type, out ITypeSymbol elementType)
        {
            elementType = null;
            if (type.SpecialType == SpecialType.System_String) return false;

            if (type is IArrayTypeSymbol arrayType)
            {
                elementType = arrayType.ElementType;
                return true;
            }

            if (type is INamedTypeSymbol namedType)
            {
                if (namedType.IsGenericType && namedType.ConstructedFrom.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
                {
                    elementType = namedType.TypeArguments[0];
                    return true;
                }

                var enumerableInterface = namedType.AllInterfaces.FirstOrDefault(i =>
                    i.IsGenericType && i.ConstructedFrom.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T);

                if (enumerableInterface != null)
                {
                    elementType = enumerableInterface.TypeArguments[0];
                    return true;
                }
            }

            return false;
        }

        private Dictionary<string, string[]> GetProxyMappings(IPropertySymbol prop, string[] baseModels)
        {
            var proxyAttrs = prop.GetAttributes().Where(a => a.AttributeClass != null && a.AttributeClass.Name == "PathProxyAttribute").ToList();
            var result = new Dictionary<string, string[]>();

            if (proxyAttrs.Count == 0)
            {
                result[prop.Name] = baseModels;
                return result;
            }

            string fallbackTo = null;

            foreach (var attr in proxyAttrs)
            {
                var args = attr.ConstructorArguments;
                if (args.Length == 2)
                {
                    var to = (string)args[0].Value;
                    var fromArr = args[1].Values.Select(v => (string)v.Value).Cast<string>().ToArray();
                    result[to] = fromArr;
                }
                else if (args.Length == 1)
                {
                    fallbackTo = (string)args[0].Value;
                }
            }

            if (fallbackTo != null)
            {
                result[fallbackTo] = Array.Empty<string>();
            }
            else if (result.Count == 0)
            {
                result[prop.Name] = baseModels;
            }

            return result;
        }
    }
}