<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NSLProjectTypes>ASPTarget</NSLProjectTypes>

		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Snapshotter\NSL.Snapshotter\NSL.Snapshotter.csproj" />
	</ItemGroup>
</Project>
