<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NSLProjectTypes>UnitySupport;AnalyzerUtils;AnalyzerCore;Unpacking</NSLProjectTypes>

		<TargetFramework>netstandard2.0</TargetFramework>
		<Configurations>DebugExamples;Debug;Release;UnityDebug;Unity</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<IsRoslynComponent>true</IsRoslynComponent>

		<Version>$(VersionSuffix)</Version>
		<Authors>Relife87</Authors>
		<Description>-</Description>

		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<PackageId>$(MSBuildProjectName)_Debug</PackageId>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='UnityDebug'">
		<AssemblyName>Unity.$(MSBuildProjectName)</AssemblyName>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Unity'">
		<AssemblyName>Unity.$(MSBuildProjectName)</AssemblyName>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug' Or '$(Configuration)'=='Release' Or '$(Configuration)'=='DebugExamples'">
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='UnityDebug' Or '$(Configuration)'=='Unity'">
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.Bcl.Numerics" Version="10.0.8" />
	</ItemGroup>


	<!--<ItemGroup>
		<ProjectReference Include="..\NSL.ShaderVM.Shared\NSL.ShaderVM.Shared.csproj" />
		<ProjectReference Include="..\NSL.ShaderVM.Core\NSL.ShaderVM.Core.csproj" PrivateAssets="all" />
		<ProjectReference Include="..\NSL.ShaderVM.Vulkan.Shared\NSL.ShaderVM.Vulkan.Shared.csproj" />
	</ItemGroup>-->

	<ItemGroup>
		<Compile Include="..\..\NSL.Generators.Utils\**\*.cs" Exclude="..\..\NSL.Generators.Utils\**\bin\**;..\..\NSL.Generators.Utils\**\obj\**">
			<Link>NSL.Generators.Utils\%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\NSL.ShaderVM.Shared\**\*.cs" Exclude="..\NSL.ShaderVM.Shared\**\bin\**;..\NSL.ShaderVM.Shared\**\obj\**">
			<Link>NSL.ShaderVM.Shared\%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>
		<Compile Include="..\NSL.ShaderVM.Core\**\*.cs" Exclude="..\NSL.ShaderVM.Core\**\bin\**;..\NSL.ShaderVM.Core\**\obj\**">
			<Link>NSL.ShaderVM.Core\%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>
		<Compile Include="..\NSL.ShaderVM.Vulkan.Shared\**\*.cs" Exclude="..\NSL.ShaderVM.Vulkan.Shared\**\bin\**;..\NSL.ShaderVM.Vulkan.Shared\**\obj\**">
			<Link>NSL.ShaderVM.Vulkan.Shared\%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>
	</ItemGroup>

</Project>
