<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NSLProjectTypes>Test</NSLProjectTypes>

		<TargetFramework>net10.0</TargetFramework>
		<Configurations>DebugExamples</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

		<Version>$(VersionSuffix)</Version>
		<Authors>Relife87</Authors>

		<IsPackable>false</IsPackable>
		<DefineConstants>$(DefineConstants);NSL_CLIENT</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<PackageId>$(MSBuildProjectName)_Debug</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\ASPNET\NSL.ASPNET\NSL.ASPNET.csproj" />
		<ProjectReference Include="..\..\..\..\Protocols\Http\NSL.HttpClient\NSL.HttpClient.csproj" />
		<ProjectReference Include="..\..\NSL.Generators.HttpEndPointGenerator.Core\NSL.Generators.HttpEndPointGenerator.Core.csproj" PrivateAssets="all" OutputItemType="Analyzer" />
	</ItemGroup>

</Project>
