<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NSLProjectTypes>AnalyzerPackage</NSLProjectTypes>

		<TargetFramework>netstandard2.0</TargetFramework>
		<IsPackable>true</IsPackable>
		<PackageId>NSL.ShaderVM.Vulkan</PackageId>
		<Version>$(VersionSuffix)</Version>
		<Authors>Relife87</Authors>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\NSL.ShaderVM.Vulkan.Core\NSL.ShaderVM.Vulkan.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(OutputPath)\*NSL.*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
	</ItemGroup>
</Project>
