dist: xenial
sudo: false
language: csharp
dotnet: 2.2.402
matrix:
  include:
    - mono: none
      env: DOTNETCORE=1
    - mono: latest
script:
  - git fetch --unshallow # in order to make Nerdbank.GitVersioning.Tasks.GetBuildVersion work
  - ./test-by-travis.sh
