<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NSLProjectTypes>UnitySupport;Core</NSLProjectTypes>

		<TargetFramework>net10.0</TargetFramework>
		<Configurations>DebugExamples;Debug;Release;UnityDebug;Unity</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

		<Version>$(VersionSuffix)</Version>
		<Authors>Relife87</Authors>
		<Description>Библиотека содержащая базовые классы для взаимодействия по сетевому протоколу TCP</Description>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<PackageId>$(MSBuildProjectName)_Debug</PackageId>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='UnityDebug'">
		<AssemblyName>Unity.$(MSBuildProjectName)</AssemblyName>
		<TargetFramework>netstandard2.1</TargetFramework>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Unity'">
		<AssemblyName>Unity.$(MSBuildProjectName)</AssemblyName>
		<TargetFramework>netstandard2.1</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Memory" Version="4.6.3" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
		<PackageReference Include="System.Threading.Channels" Version="8.0.0" Condition="'$(TargetFramework)' == 'netstandard2.1'" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Utils\NSL.Utils\NSL.Utils.csproj" />
		<ProjectReference Include="..\..\Generators\NSL.Generators.BinaryTypeIOGenerator\NSL.Generators.BinaryTypeIOGenerator.Shared\NSL.Generators.BinaryTypeIOGenerator.Shared.csproj" />
		<ProjectReference Include="..\..\Generators\NSL.Generators.BinaryTypeIOGenerator\NSL.Generators.BinaryTypeIOGenerator.Core\NSL.Generators.BinaryTypeIOGenerator.Core.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" OutputItemType="Analyzer" />
	</ItemGroup>

</Project>
