<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NSLProjectTypes>ASPTarget</NSLProjectTypes>

		<TargetFramework>net10.0</TargetFramework>
		<Configurations>DebugExamples;Debug;Release</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>
		<IsPackable>true</IsPackable>
		<OutputType>Library</OutputType>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

		<Version>$(VersionSuffix)</Version>
		<Authors>Relife87</Authors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<PackageId>$(MSBuildProjectName)_Debug</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\Database\Filter\NSL.Database.EntityFramework.Filter.V2\NSL.Database.EntityFramework.Filter.V2.csproj" />
		<ProjectReference Include="..\..\..\..\Protocols\Http\NSL.HttpClient\NSL.HttpClient.csproj" />
	</ItemGroup>

</Project>
