@NSL.ASPNET.Test_HostAddress = http://localhost:5029

POST {{NSL.ASPNET.Test_HostAddress}}/Home/Index
Accept: application/json

###
POST {{NSL.ASPNET.Test_HostAddress}}/Home/Error400
Content-Type: application/json
Accept: application/json
{
  "A": "aaaa"
}

###
