<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<NSLProjectTypes>Example</NSLProjectTypes>

		<TargetFramework>net10.0</TargetFramework>
		<Configurations>DebugExamples</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

		<Version>$(VersionSuffix)</Version>
		<Authors>Relife87</Authors>

		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<PackageId>$(MSBuildProjectName)_Debug</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\NSL.Node.BridgeLobbyClient.AspNetCore\NSL.Node.BridgeLobbyClient.AspNetCore.csproj" />
		<ProjectReference Include="..\..\NSL.Node.BridgeServer.AspNetCore\NSL.Node.BridgeServer.AspNetCore.csproj" />
	</ItemGroup>

</Project>
