<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NSLProjectTypes>Test</NSLProjectTypes>

		<TargetFramework>net10.0</TargetFramework>
		<Configurations>DebugExamples</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

		<Version>$(VersionSuffix)</Version>
		<Authors>Relife87</Authors>

		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<PackageId>$(MSBuildProjectName)_Debug</PackageId>
	</PropertyGroup>

</Project>
