<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NSLProjectTypes>ASPTarget</NSLProjectTypes>

		<TargetFramework>net10.0</TargetFramework>
		<Configurations>DebugExamples;Debug;Release</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>
		<IsPackable>true</IsPackable>
		<OutputType>Library</OutputType>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

		<Version>$(VersionSuffix)</Version>
		<Authors>Relife87</Authors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<PackageId>$(MSBuildProjectName)_Debug</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Base\NSL.Logger\NSL.Logger.csproj" />
	</ItemGroup>

</Project>
