<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NSLProjectTypes>UnitySupport;AnalyzerUtils;Unpacking</NSLProjectTypes>

		<TargetFramework>netstandard2.0</TargetFramework>
		<Configurations>DebugExamples;Debug;Release;UnityDebug;Unity</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

		<Version>$(VersionSuffix)</Version>
		<Authors>Relife87</Authors>
		<Description>-</Description>

		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<PackageId>$(MSBuildProjectName)_Debug</PackageId>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='UnityDebug'">
		<AssemblyName>Unity.$(MSBuildProjectName)</AssemblyName>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Unity'">
		<AssemblyName>Unity.$(MSBuildProjectName)</AssemblyName>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug' Or '$(Configuration)'=='Release' Or '$(Configuration)'=='DebugExamples'">
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.3.0" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='UnityDebug' Or '$(Configuration)'=='Unity'">
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.3.1" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\NSL.Generators.Utils\NSL.Generators.Utils.csproj" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\..\Core\NSL.SocketCore\**\*.cs" Exclude="..\..\Core\NSL.SocketCore\**\bin\**;..\..\Core\NSL.SocketCore\**\obj\**;..\..\Core\NSL.SocketCore\**\Network\**">
			<Link>NSL.SocketCore\%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>


		<Compile Include="..\..\Core\Utils\NSL.Utils\**\*.cs" Exclude="..\..\Core\Utils\NSL.Utils\**\bin\**;..\..\Core\Utils\NSL.Utils\**\obj\**">
			<Link>NSL.Utils\%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="..\..\Core\Utils\NSL.Utils\CommandLine\**" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="..\..\Core\Utils\NSL.Utils\IOUtils.cs" />
		<Compile Remove="..\..\Core\Utils\NSL.Utils\NSLConsoleOutput.cs" />
		<Compile Remove="..\..\Core\Utils\NSL.Utils\PermissionUtils.cs" />
		<Compile Remove="..\..\Core\Utils\NSL.Utils\Token.cs" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
	</ItemGroup>


</Project>
