<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NSLProjectTypes>Example</NSLProjectTypes>
    <Configurations>DebugExamples</Configurations>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <Version>$(VersionSuffix)</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Base\NSL.Logger\NSL.Logger.csproj" />
    <ProjectReference Include="..\..\Open.NAT\NSL.Open.Nat\NSL.Open.Nat.csproj" />
    <ProjectReference Include="..\NSL.UDPExample\NSL.UDPExample.csproj" />
  </ItemGroup>
</Project>