using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using NSL.Generators.BinaryGenerator;
using NSL.Generators.BinaryTypeIOGenerator.Shared;
using NSL.Generators.RpcGenerator.Core.Utils;
using NSL.Generators.RpcGenerator.Shared;
using NSL.Generators.RpcGenerator.Shared.Attributes;
using NSL.Generators.Utils;
using NSL.SocketCore;
using NSL.SocketCore.Utils;
using NSL.SocketCore.Utils.Buffer;
using System;
using System.Collections.Generic;
using System.Linq;

namespace NSL.Generators.RpcGenerator.Core
{
    [Generator]
    internal class NSLRPCGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var pip = context.SyntaxProvider.CreateSyntaxProvider(
                NSLRPCSyntaxReceiver.OnVisitSyntaxNode,
                (syntax, _) => syntax);

            context.RegisterSourceOutput(pip, ProcessRpcType);
        }

        private void ProcessRpcType(SourceProductionContext context, GeneratorSyntaxContext item)
        {
            var @class = (ClassDeclarationSyntax)item.Node;
            try
            {
                ProcessRpcClass(context, item, @class);
            }
            catch (Exception ex)
            {
                context.ShowRpcDiagnostics("NSLRPC999", $"Error on build {ex}", DiagnosticSeverity.Error, @class.GetLocation());
            }
        }

        private void ProcessRpcClass(SourceProductionContext sourceContext, GeneratorSyntaxContext context, ClassDeclarationSyntax typeClass)
        {
            if (!typeClass.HasPartialModifier())
            {
                sourceContext.ShowRpcDiagnostics("NSLRPC000", "Type must have a partial modifier", DiagnosticSeverity.Error, typeClass.GetLocation());
                return;
            }

            var typeSem = context.SemanticModel;
            var codeBuilder = new CodeBuilder();

            codeBuilder.AppendComment(() =>
            {
                codeBuilder.AppendLine("Auto Generated by NSL RPC Generator. Please don't change this file");
                codeBuilder.AppendLine("Project must have reference to \"NSL.SocketCore\" for normal working");
            });

            List<string> usings = new List<string>
            {
                "NSL.SocketCore",
                "NSL.SocketCore.Utils.Buffer",
                "NSL.SocketCore.Utils.Request",
                "NSL.Generators.RpcGenerator.Shared",
                "System",
                "System.Linq",
                "System.Threading",
                "System.Threading.Tasks"
            };

            codeBuilder.CreatePartialClass((CSharpCompilation)typeSem.Compilation, typeClass, classBuilder =>
            {
                var implAttrs = typeClass.AttributeLists
                    .SelectMany(x => x.Attributes)
                    .Where(x => x.GetAttributeFullName().Equals(NSLRPCImplementAttributeFullName))
                    .ToArray();

                var containers = new List<RpcContainerData>();
                bool hasClientSide = false;

                foreach (var attr in implAttrs)
                {
                    var container = ReadContainerData(sourceContext, typeSem, attr);
                    if (container == null) continue;

                    containers.Add(container);

                    if (container.Direction.HasFlag(NSLRPCDirection.Client))
                        hasClientSide = true;
                }

                if (hasClientSide)
                {
                    classBuilder.AppendLine("protected partial NSL.Generators.RpcGenerator.Shared.IRPCNetworkChannel GetRpcChannel();");
                    classBuilder.AppendLine();
                }

                foreach (var container in containers)
                {
                    // Add usings from interface's file
                    var syntaxRef = container.InterfaceType.DeclaringSyntaxReferences.FirstOrDefault();
                    if (syntaxRef != null)
                    {
                        var root = syntaxRef.SyntaxTree.GetRoot();
                        root.DescendantNodes()
                            .OfType<UsingDirectiveSyntax>()
                            .Select(u => string.Join(" ", u.ToString().Split(' ').Skip(1)).TrimEnd(';').Trim())
                            .ToList()
                            .ForEach(u => usings.Add(u));
                    }

                    if (container.Direction.HasFlag(NSLRPCDirection.Client))
                        BuildClientCode(sourceContext, classBuilder, container);

                    if (container.Direction.HasFlag(NSLRPCDirection.Server))
                        BuildServerCode(sourceContext, classBuilder, container);
                }

            }, usings);

            sourceContext.AddSource($"{typeClass.GetTypeClassName()}.rpc.cs", codeBuilder.ToString());
        }

        // ── Client side ─────────────────────────────────────────────────────────

        private void BuildClientCode(SourceProductionContext sourceContext, CodeBuilder classBuilder, RpcContainerData container)
        {
            foreach (var method in container.Methods)
            {
                BuildClientMethod(sourceContext, classBuilder, container, method);
                classBuilder.AppendLine();
            }
        }

        private void BuildClientMethod(SourceProductionContext sourceContext, CodeBuilder classBuilder, RpcContainerData container, RpcMethodData method)
        {
            classBuilder.AppendSummaryLine($"RPC client stub for <see cref=\"{container.InterfaceType.GetTypeFullName()}.{method.Name}\"/>. Pid = {method.Pid}");

            if (method.IsFireAndForget)
            {
                // FAF: void return, OutputPacketBuffer, GetRpcChannel().Send()
                var fafParams = method.Parameters.Select(p => $"{p.Type.GetTypeFullName()} {p.Name}").ToList();
                classBuilder.AppendLine($"public void {method.Name}({string.Join(", ", fafParams)})");
                classBuilder.AppendBodyTabContent(() =>
                {
                    classBuilder.AppendLine($"var __outputBuf = {nameof(OutputPacketBuffer)}.Create({method.Pid});");
                    foreach (var p in method.Parameters)
                        classBuilder.AppendLine($"{BuildParamWriteSegment(sourceContext, p, p.Name, "__outputBuf")};");
                    classBuilder.AppendLine();
                    classBuilder.AppendLine("GetRpcChannel().Send(__outputBuf);");
                });
                return;
            }

            // Default: request-response (Task or Task<T>)
            bool hasResult = method.Result != null;
            var reqParams = method.Parameters.Select(p => $"{p.Type.GetTypeFullName()} {p.Name}").ToList();
            reqParams.Add("System.Threading.CancellationToken __cancellationToken = default");

            string returnType = hasResult
                ? $"async Task<{method.Result.Type.GetTypeFullName()}>"
                : "async Task";

            classBuilder.AppendLine($"public {returnType} {method.Name}({string.Join(", ", reqParams)})");
            classBuilder.AppendBodyTabContent(() =>
            {
                classBuilder.AppendLine($"var __outputBuf = RequestPacketBuffer.Create({method.Pid});");
                foreach (var p in method.Parameters)
                    classBuilder.AppendLine($"{BuildParamWriteSegment(sourceContext, p, p.Name, "__outputBuf")};");

                classBuilder.AppendLine();
                classBuilder.AppendLine("using var __response = await GetRpcChannel().RequestAsync(__outputBuf, __cancellationToken);");

                if (method.HasExceptionHandler)
                {
                    classBuilder.AppendLine("if (!__response.ReadBool())");
                    classBuilder.AppendBodyTabContent(() =>
                        classBuilder.AppendLine("throw new NSLRPCRemoteException(__response.ReadString(), __response.ReadString());"));
                }

                if (hasResult)
                {
                    classBuilder.AppendLine();
                    classBuilder.AppendLine($"return {BuildResultReadSegment(sourceContext, method.Result, method.Result.Type.GetTypeFullName(), "__response")};");
                }
            });
        }

        // ── Server side ─────────────────────────────────────────────────────────

        private void BuildServerCode(SourceProductionContext sourceContext, CodeBuilder classBuilder, RpcContainerData container)
        {
            var configureBuilder = new CodeBuilder();

            configureBuilder.AppendLine($"public void NSLConfigureRpcHandles_{container.InterfaceType.Name}({nameof(CoreOptions)}<{container.NetworkDataType.GetTypeFullName()}> options)");
            configureBuilder.AppendBodyTabContent(() =>
            {
                foreach (var method in container.Methods)
                {
                    BuildServerHandler(sourceContext, classBuilder, container, method);
                    classBuilder.AppendLine();

                    configureBuilder.AppendLine($"options.{nameof(CoreOptions<BaseNetworkConnection>.AddAsyncHandle)}({method.Pid}, NSLRpcHandle_{method.Name});");
                }
            });

            classBuilder.AppendLine(configureBuilder.ToString());
        }

        private void BuildServerHandler(SourceProductionContext sourceContext, CodeBuilder classBuilder, RpcContainerData container, RpcMethodData method)
        {
            string clientType = container.NetworkDataType.GetTypeFullName();
            bool hasResult = method.Result != null;

            classBuilder.AppendSummaryLine($"RPC server handler for <see cref=\"{container.InterfaceType.GetTypeFullName()}.{method.Name}\"/>. Pid = {method.Pid}");
            classBuilder.AppendLine($"private async System.Threading.Tasks.Task NSLRpcHandle_{method.Name}({clientType} client, {nameof(InputPacketBuffer)} data)");
            classBuilder.AppendBodyTabContent(() =>
            {
                // FAF: no response at all
                if (method.IsFireAndForget)
                {
                    foreach (var p in method.Parameters)
                        classBuilder.AppendLine($"{p.Type.GetTypeFullName()} {p.Name} = {BuildParamReadSegment(sourceContext, p, p.Type.GetTypeFullName(), "data")};");
                    classBuilder.AppendLine();
                    classBuilder.AppendLine($"await {method.Name}({string.Join(", ", method.Parameters.Select(p => p.Name))});");
                    return;
                }

                // Request-response
                classBuilder.AppendLine("var __response = data.CreateResponse();");
                classBuilder.AppendLine();

                foreach (var p in method.Parameters)
                    classBuilder.AppendLine($"{p.Type.GetTypeFullName()} {p.Name} = {BuildParamReadSegment(sourceContext, p, p.Type.GetTypeFullName(), "data")};");

                var callArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
                classBuilder.AppendLine();

                if (method.HasExceptionHandler)
                {
                    classBuilder.AppendLine("try");
                    classBuilder.AppendBodyTabContent(() => BuildServerInvoke(sourceContext, classBuilder, method, callArgs, hasResult, "__response", writeSuccessFlag: true));
                    classBuilder.AppendLine("catch (System.Exception __ex)");
                    classBuilder.AppendBodyTabContent(() =>
                    {
                        classBuilder.AppendLine("__response.WriteBool(false);");
                        classBuilder.AppendLine("__response.WriteString(__ex.GetType().FullName);");
                        classBuilder.AppendLine("__response.WriteString(__ex.Message);");
                    });
                }
                else
                {
                    BuildServerInvoke(sourceContext, classBuilder, method, callArgs, hasResult, "__response", writeSuccessFlag: false);
                }

                classBuilder.AppendLine();
                classBuilder.AppendLine("client.Send(__response);");
            });
        }

        private void BuildServerInvoke(SourceProductionContext sourceContext, CodeBuilder classBuilder, RpcMethodData method, string callArgs, bool hasResult, string responseBuf, bool writeSuccessFlag)
        {
            if (hasResult)
            {
                classBuilder.AppendLine($"var ___result = await {method.Name}({callArgs});");
                if (writeSuccessFlag)
                    classBuilder.AppendLine($"{responseBuf}.WriteBool(true);");
                classBuilder.AppendLine($"{BuildResultWriteSegment(sourceContext, method.Result, "___result", responseBuf)};");
            }
            else
            {
                classBuilder.AppendLine($"await {method.Name}({callArgs});");
                if (writeSuccessFlag)
                    classBuilder.AppendLine($"{responseBuf}.WriteBool(true);");
            }
        }

        // ── Binary serialization helpers ─────────────────────────────────────────

        private string BuildParamReadSegment(SourceProductionContext sourceContext, RpcParamData param, string typeName, string ioPath)
        {
            var typeAttributes = param.Type.GetAttributes()
                .Where(x => x.AttributeClass.Name.Equals(NSLBIOTypeAttributeFullName)).ToArray();

            var typeModels = typeAttributes
                .SelectMany(x => x.ConstructorArguments.SelectMany(n => n.Values.Select(d => (string)d.Value)))
                .DefaultIfEmpty("<!!_NSLBIOFULL_!!>")
                .GroupBy(x => x).Select(x => x.Key)
                .ToArray();

            var model = param.BinaryModel ?? "<!!_NSLBIOFULL_!!>";

            if (typeAttributes.Length > 0 && typeModels.Contains(model))
            {
                return param.BinaryModel == null
                    ? $"{typeName}.ReadFullFrom({ioPath})"
                    : $"{typeName}.Read{param.BinaryModel}From({ioPath})";
            }

            return BinaryReadMethodsGenerator.GetValueReadSegment(param.Type, new BinaryGeneratorContext
            {
                Context = sourceContext,
                IOPath = ioPath,
                For = model
            }, ioPath);
        }

        private string BuildParamWriteSegment(SourceProductionContext sourceContext, RpcParamData param, string valueName, string ioPath)
        {
            var typeAttributes = param.Type.GetAttributes()
                .Where(x => x.AttributeClass.Name.Equals(NSLBIOTypeAttributeFullName)).ToArray();

            var typeModels = typeAttributes
                .SelectMany(x => x.ConstructorArguments.SelectMany(n => n.Values.Select(d => (string)d.Value)))
                .DefaultIfEmpty("<!!_NSLBIOFULL_!!>")
                .GroupBy(x => x).Select(x => x.Key)
                .ToArray();

            var model = param.BinaryModel ?? "<!!_NSLBIOFULL_!!>";

            if (typeAttributes.Length > 0 && typeModels.Contains(model))
            {
                return param.BinaryModel == null
                    ? $"{valueName}.WriteFullTo({ioPath})"
                    : $"{valueName}.Write{param.BinaryModel}To({ioPath})";
            }

            return BinaryWriteMethodsGenerator.BuildParameterWriter(param.Type, new BinaryGeneratorContext
            {
                Context = sourceContext,
                IOPath = ioPath,
                For = model
            }, valueName);
        }

        private string BuildResultReadSegment(SourceProductionContext sourceContext, RpcResultData result, string typeName, string ioPath)
        {
            var typeAttributes = result.Type.GetAttributes()
                .Where(x => x.AttributeClass.Name.Equals(NSLBIOTypeAttributeFullName)).ToArray();

            var typeModels = typeAttributes
                .SelectMany(x => x.ConstructorArguments.SelectMany(n => n.Values.Select(d => (string)d.Value)))
                .DefaultIfEmpty("<!!_NSLBIOFULL_!!>")
                .GroupBy(x => x).Select(x => x.Key)
                .ToArray();

            var model = result.BinaryModel ?? "<!!_NSLBIOFULL_!!>";

            if (typeAttributes.Length > 0 && typeModels.Contains(model))
            {
                return result.BinaryModel == null
                    ? $"{typeName}.ReadFullFrom({ioPath})"
                    : $"{typeName}.Read{result.BinaryModel}From({ioPath})";
            }

            return BinaryReadMethodsGenerator.GetValueReadSegment(result.Type, new BinaryGeneratorContext
            {
                Context = sourceContext,
                IOPath = ioPath,
                For = model
            }, ioPath).TrimEnd(';');
        }

        private string BuildResultWriteSegment(SourceProductionContext sourceContext, RpcResultData result, string valueName, string ioPath)
        {
            var typeAttributes = result.Type.GetAttributes()
                .Where(x => x.AttributeClass.Name.Equals(NSLBIOTypeAttributeFullName)).ToArray();

            var typeModels = typeAttributes
                .SelectMany(x => x.ConstructorArguments.SelectMany(n => n.Values.Select(d => (string)d.Value)))
                .DefaultIfEmpty("<!!_NSLBIOFULL_!!>")
                .GroupBy(x => x).Select(x => x.Key)
                .ToArray();

            var model = result.BinaryModel ?? "<!!_NSLBIOFULL_!!>";

            if (typeAttributes.Length > 0 && typeModels.Contains(model))
            {
                return result.BinaryModel == null
                    ? $"{valueName}.WriteFullTo({ioPath})"
                    : $"{valueName}.Write{result.BinaryModel}To({ioPath})";
            }

            return BinaryWriteMethodsGenerator.BuildParameterWriter(result.Type, new BinaryGeneratorContext
            {
                Context = sourceContext,
                IOPath = ioPath,
                For = model
            }, valueName).TrimEnd(';');
        }

        // ── Data reading ─────────────────────────────────────────────────────────

        private RpcContainerData ReadContainerData(SourceProductionContext sourceContext, SemanticModel typeSem, AttributeSyntax attr)
        {
            var args = attr.ArgumentList?.Arguments;
            if (args == null || args.Value.Count < 2)
            {
                sourceContext.ShowRpcDiagnostics("NSLRPC001", "NSLRPCImplementAttribute requires Interface and NetworkDataType", DiagnosticSeverity.Error, attr.GetLocation());
                return null;
            }

            var interfaceType = args.Value[0].GetAttributeTypeParameterValueSymbol(typeSem);
            var networkDataType = args.Value[1].GetAttributeTypeParameterValueSymbol(typeSem);

            if (interfaceType == null || networkDataType == null)
            {
                sourceContext.ShowRpcDiagnostics("NSLRPC002", "Cannot resolve Interface or NetworkDataType type argument", DiagnosticSeverity.Error, attr.GetLocation());
                return null;
            }

            var direction = NSLRPCDirection.Both;

            var namedArgs = args.Value.Where(a => a.NameEquals != null).ToDictionary(a => a.NameEquals.Name.ToString(), a => a);

            if (namedArgs.TryGetValue(nameof(NSLRPCImplementAttribute.Direction), out var dirArg))
                direction = dirArg.GetAttributeParameterValue<NSLRPCDirection>(typeSem);

            bool interfaceHasExceptionHandler = interfaceType.GetAttributes()
                .Any(a => a.AttributeClass.Name.Equals(NSLRPCExceptionHandlerAttributeFullName));

            var container = new RpcContainerData
            {
                InterfaceType = interfaceType,
                NetworkDataType = networkDataType,
                Direction = direction
            };

            LoadMethods(sourceContext, typeSem, container, interfaceHasExceptionHandler);

            return container;
        }

        private void LoadMethods(SourceProductionContext sourceContext, SemanticModel typeSem, RpcContainerData container, bool interfaceHasExceptionHandler)
        {
            foreach (var member in container.InterfaceType.GetAllMembers())
            {
                if (!(member is IMethodSymbol ms))
                    continue;

                var methodAttrs = ms.GetAttributes();

                var rpcAttr = methodAttrs.FirstOrDefault(a => a.AttributeClass.Name.Equals(NSLRPCMethodAttributeFullName));
                if (rpcAttr == null)
                    continue;

                var pid = (ushort)rpcAttr.ConstructorArguments[0].Value;

                string binaryModel = null;
                var binaryModelArg = rpcAttr.NamedArguments.FirstOrDefault(n => n.Key == nameof(NSLRPCMethodAttribute.BinaryModel));
                if (!binaryModelArg.Equals(default) && binaryModelArg.Value.Value is string bm && !string.IsNullOrEmpty(bm))
                    binaryModel = bm;

                bool isFireAndForget = methodAttrs.Any(a => a.AttributeClass.Name.Equals(NSLRPCFireAndForgetAttributeFullName));

                bool hasExceptionHandler = !isFireAndForget && (
                    interfaceHasExceptionHandler ||
                    methodAttrs.Any(a => a.AttributeClass.Name.Equals(NSLRPCExceptionHandlerAttributeFullName)));

                // Determine result: Task<T> → T, plain Task → null
                RpcResultData result = null;
                if (!isFireAndForget)
                {
                    var returnType = ms.ReturnType as INamedTypeSymbol;
                    if (returnType != null && returnType.TypeArguments.Length == 1)
                    {
                        result = new RpcResultData
                        {
                            Type = returnType.TypeArguments[0],
                            BinaryModel = binaryModel
                        };
                    }
                }

                var parameters = ms.Parameters.Select(p => new RpcParamData
                {
                    Type = p.Type,
                    Name = p.Name,
                    BinaryModel = binaryModel
                }).ToArray();

                container.Methods.Add(new RpcMethodData
                {
                    Name = ms.Name,
                    Pid = pid,
                    Parameters = parameters,
                    Result = result,
                    IsFireAndForget = isFireAndForget,
                    HasExceptionHandler = hasExceptionHandler,
                    MethodSymbol = ms
                });
            }
        }

        // ── Constants ────────────────────────────────────────────────────────────

        internal static readonly string NSLRPCImplementAttributeFullName        = typeof(NSLRPCImplementAttribute).Name;
        internal static readonly string NSLRPCMethodAttributeFullName           = typeof(NSLRPCMethodAttribute).Name;
        internal static readonly string NSLRPCFireAndForgetAttributeFullName    = typeof(NSLRPCFireAndForgetAttribute).Name;
        internal static readonly string NSLRPCExceptionHandlerAttributeFullName = typeof(NSLRPCExceptionHandlerAttribute).Name;
        internal static readonly string NSLBIOTypeAttributeFullName             = typeof(NSLBIOTypeAttribute).Name;
    }
}
