<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NSLProjectTypes>Example</NSLProjectTypes>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <Version>$(VersionSuffix)</Version>
    <Configurations>DebugExamples</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Base\NSL.Logger\NSL.Logger.csproj" />
    <ProjectReference Include="..\..\..\Protocols\TCP\NSL.TCP.Client\NSL.TCP.Client.csproj" />
    <ProjectReference Include="..\..\..\Protocols\TCP\NSL.TCP.Server\NSL.TCP.Server.csproj" />
  </ItemGroup>
</Project>